### ISSUE TITLE
Error when auto-importing a Svelte file that uses typescript internally

### ISSUE THREAD

**Issue by josiah-redjade** [Mohamed-Kaizen/unplugin-svelte-components#13]
This breaks in webpack when importing a Svelte file with `<script lang="ts">`, and any sort of Typescript specific syntax. To avoid this, there should be an option to pass in a preprocessor (i.e., svelte-preprocess) in the options when initializing Unplugin Svelte.

For instance, 

```
<script lang="ts">
  let classes: string = ""
  export { classes as class }
</script>

<section class="{classes} p-wide">
  <slot />
</section>
```

Will yield this error:

```
file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13140
    const error = new CompileError(message);
                  ^

CompileError [ParseError]: Unexpected token
    at error (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13140:19)
    at Parser$1.error (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13218:9)
    at Parser$1.acorn_error (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13212:14)
    at Object.read_script [as read] (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:8999:16)
    at tag (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:12164:33)
    at new Parser$1 (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13177:21)
    at parse$a (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/svelte/compiler.mjs:13317:20)
    at transformComponent (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/unplugin-svelte-components/chunk-A7SKBKDC.js:347:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.transformer (file:///Users/josiahsprankle/Desktop/Redjade/RedJade/clients/node_modules/unplugin-svelte-components/chunk-A7SKBKDC.js:313:5) {
  code: 'parse-error',
  start: { line: 2, column: 13, character: 32 },
  end: { line: 2, column: 13, character: 32 },
  pos: 32,
  filename: undefined,
  frame: '1: <script lang="ts">\n' +
    '2:   let classes: string = ""\n' +
    '                ^\n' +
    '3:   export { classes as class }\n' +
    '4: </script>'
    ```

**Comment by josiah-redjade** [comment]
Fixed with PR #14
